name: AMPiQ CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install root dependencies
      run: npm install
    - name: Install extension GUI dependencies
      run: npm run install-deps
    - name: Run tests
      run: npm test
    - name: Build extension GUI
      run: npm run build
    - name: Create build artifacts
      run: |
        mkdir -p dist
        cp -r desktop-ui/dist/* dist/ || true
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ampiq-build-${{ matrix.node-version }}
        path: dist/
        retention-days: 30
